Logging ...

diff --git a/templates/default/backup_sh.erb b/templates/default/backup_sh.erb
--- a/templates/default/backup_sh.erb
+++ b/templates/default/backup_sh.erb
@@ -12,30 +12,49 @@ LOG=$MFLUX_HOME/volatile/logs/backups.log
 REPLICA=<%= @replica %>
 KEEP_DAYS=<%= @keep_days %>
 
-find $DIR -type f -ctime -$KEEP_DAYS -exec rm {} ";"
-find $DIR -mindepth 1 -type d -ctime -$KEEP_DAYS \
-    -exec rmdir --ignore-fail-on-non-empty "{}" ";"
+echo "*** Starting backup run - " `date` >> $LOG
 
-TODAY=${DIR}/`date +%F`
+echo "Cleaning old backups" >> $LOG
+find $DIR -type f -ctime -$KEEP_DAYS -exec rm {} \; >> $LOG 2>&1
+find $DIR -mindepth 1 -type d -ctime -$KEEP_DAYS \
+    -exec rmdir --ignore-fail-on-non-empty \{\} \; >> $LOG 2>&1
+
+TODAY=`date +%F`
+TODAY_DIR=$DIR/$TODAY
 
 if [ ! -e $TODAY ] ; then
-    mkdir $TODAY
-    chown $MFLUX_SYSTEM_USER:$MFLUX_SYSTEM_USER $TODAY
+    echo "Creating backup directory $TODAY_DIR" >> $LOG
+    mkdir $TODAY_DIR
+    chown $MFLUX_SYSTEM_USER:$MFLUX_SYSTEM_USER $TODAY_DIR
+    chmod 750 $TODAY_DIR
 fi
 
+echo "Running backup for $TODAY" >> $LOG
 MF_COMMAND="$MFLUX_BIN/mfcommand"
 $MF_COMMAND logon $MFLUX_DOMAIN $MFLUX_USER "$MFLUX_PASSWORD"
-$MF_COMMAND source -dir=$TODAY $MFLUX_HOME/config/daris_backup.tcl
+$MF_COMMAND source -dir=$TODAY_DIR $MFLUX_HOME/config/daris_backup.tcl
 RC=$?
 $MF_COMMAND logoff
 
-if [ ! -z "$REPLICA" -a $RC -eq 0 ] ; then
+if [ $RC -eq 0 ] ; then
+    echo "Backup for $TODAY completed" >> $LOG
+else
+    echo "Backup for $TODAY failed" >> $LOG
+    echo "Mediaflux backup for $TODAY failed; see log file"
+    exit $RC
+fi
+
+if [ ! -z "$REPLICA" ] ; then
+    echo "Rsyncing backups" >> $LOG
+    OPTS="-av --dry-run --delete-before"
     if [ `expr match $REPLICA ".+:"` -eq 0 ] ; then 
-        rsync -av --compress-level=0 --dry-run --delete-before $DIR $REPLICA
-	RC=$?
-    else
-        rsync -av --dry-run --delete-before $DIR $REPLICA
-	RC=$?
+        OPTS="$OPTS --delete-before"
+    fi
+    rsync $OPTS $DIR $REPLICA >> $LOG 2>&1
+    RC=$?
+    if [ $RC -ne 0 ] ; then
+	echo "Rsync failed" >> $LOG
+	echo "Mediaflux backup rsync failed; see log file"
     fi
 fi
 
