Attempt to fix the problems of sessions timing out and left-over locks

diff --git a/templates/default/backup_sh.erb b/templates/default/backup_sh.erb
--- a/templates/default/backup_sh.erb
+++ b/templates/default/backup_sh.erb
@@ -79,17 +79,45 @@ if [ ! -e $TODAY ] ; then
     chmod 750 $TODAY_DIR
 fi
 
-echo "*** Running mediaflux backups for $TODAY - " `$TIMESTAMP` >> $LOG
-MF_COMMAND="$MFLUX_BIN/mfcommand"
-$MF_COMMAND logon $MFLUX_DOMAIN $MFLUX_USER "$MFLUX_PASSWORD" >> $LOG 2>&1
-RC=$?
-if [ $RC -ne 0 ] ; then
-    echo "*** Mediaflux login failed ..." >> $LOG 2>&1
-else
-    $MF_COMMAND source -dir=$TODAY_DIR $MFLUX_HOME/config/backup.tcl \
-	    >> $LOG 2>&1
+mf() {
+    MF_COMMAND="$MFLUX_BIN/mfcommand"
+    $MF_COMMAND logon $MFLUX_DOMAIN $MFLUX_USER "$MFLUX_PASSWORD" >> $LOG 2>&1
     RC=$?
-    $MF_COMMAND logoff >> $LOG 2>&1
+    if [ $RC -ne 0 ] ; then
+	echo "*** Mediaflux login failed ..." >> $LOG 2>&1
+    else
+	$MF_COMMAND "$@" >> $LOG 2>&1
+	RC=$?	
+	$MF_COMMAND logoff >> $LOG 2>&1
+    fi
+}
+
+echo "*** Running mediaflux backups for $TODAY - " `$TIMESTAMP` >> $LOG
+
+mf server.database.backup :url file:///$TODAY_DIR/database
+LOCKED=1
+if [ $RC -eq 0 ] ; then
+    mf server.database.lock :action abort \
+        :msg "The Mediaflux database and stores are being backed up"
+    if [ $RC -eq 0 ] ; then
+	LOCKED=1
+    fi
+fi
+<% @stores.each do |store| %>
+RRC=$RC
+  <% if @external_asset_backup then %>
+<%= @backup_wrapper %> $TODAY_DIR <%= store %> 
+  <% else %>
+mf asset.archive.create :url file:///$TODAY_DIR/<%= store %>.aar \
+    :where content store '<%= store %>'
+  <% end %>
+if [ $RCC -ne 0 ] ; then
+    RC = $RRC
+fi
+<% end %>
+
+if [ $LOCKED -eq 1 ] ; then
+    mf server.database.unlock
 fi
 if [ $RC -eq 0 ] ; then
     echo "*** Backup for $TODAY completed - " `$TIMESTAMP` >> $LOG
